package reportes;
import jdda.ConnectionDB;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
import java.util.HashMap;
import java.util.Map;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Raúl
 */
public class Reportes extends javax.swing.JFrame {
    ConnectionDB cb  = new ConnectionDB();
    ResultSet rs;
    JasperViewer window;
    DefaultTableModel dtm;
    /**
     * Creates new form Reportes
     */
    public Reportes() {
        initComponents();
        showRegisters();   
        this.setLocationRelativeTo(null);
        
    }
    
    public void showRegisters(){
        cb.Connection("rollback", "root", "1234");
        try {
            rs = cb.query("Select nombre from clientes");
            while (rs.next()) {
                this.jcb_costumers.addItem(rs.getString("nombre"));
            }
            rs.close();
        } catch (Exception e) {
            System.err.println("llenar cliente\n"+e.getMessage());
        }
        
        try {
            rs =cb.query("Select nombre from producto");
            while (rs.next()) {
                this.jcb_products.addItem(rs.getString("nombre"));
            }
            rs.close();
        } catch (Exception e) {
            System.err.println("llenar producto\n"+e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_head = new javax.swing.JPanel();
        jp_corpo = new javax.swing.JPanel();
        jl_costumers = new javax.swing.JLabel();
        jcb_costumers = new javax.swing.JComboBox<>();
        jbtn_seachCostumers = new javax.swing.JButton();
        jcb_products = new javax.swing.JComboBox<>();
        jl_products = new javax.swing.JLabel();
        jbtn_all = new javax.swing.JButton();
        jbtn_costumers = new javax.swing.JButton();
        jbtn_products = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_data = new javax.swing.JTable();
        jbtn_seachProducts = new javax.swing.JButton();
        jl_title = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jp_head.setBackground(new java.awt.Color(245, 127, 23));

        jp_corpo.setBackground(new java.awt.Color(255, 245, 157));

        jl_costumers.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jl_costumers.setText("Cliente");

        jcb_costumers.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jbtn_seachCostumers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reportes/busqueda.png"))); // NOI18N
        jbtn_seachCostumers.setBorder(null);
        jbtn_seachCostumers.setBorderPainted(false);
        jbtn_seachCostumers.setContentAreaFilled(false);
        jbtn_seachCostumers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_seachCostumersActionPerformed(evt);
            }
        });

        jcb_products.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jl_products.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jl_products.setText("Producto");

        jbtn_all.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtn_all.setText("Todo");
        jbtn_all.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_allActionPerformed(evt);
            }
        });

        jbtn_costumers.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtn_costumers.setText("Clientes");
        jbtn_costumers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_costumersActionPerformed(evt);
            }
        });

        jbtn_products.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtn_products.setText("Productos");
        jbtn_products.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_productsActionPerformed(evt);
            }
        });

        jt_data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jt_data);

        jbtn_seachProducts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reportes/busqueda.png"))); // NOI18N
        jbtn_seachProducts.setBorder(null);
        jbtn_seachProducts.setBorderPainted(false);
        jbtn_seachProducts.setContentAreaFilled(false);
        jbtn_seachProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_seachProductsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_corpoLayout = new javax.swing.GroupLayout(jp_corpo);
        jp_corpo.setLayout(jp_corpoLayout);
        jp_corpoLayout.setHorizontalGroup(
            jp_corpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_corpoLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jp_corpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jp_corpoLayout.createSequentialGroup()
                        .addGroup(jp_corpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_costumers)
                            .addComponent(jcb_costumers, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jbtn_seachCostumers)
                        .addGap(18, 18, 18)
                        .addGroup(jp_corpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_corpoLayout.createSequentialGroup()
                                .addComponent(jl_products)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jcb_products, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(39, 39, 39)
                        .addComponent(jbtn_seachProducts))
                    .addGroup(jp_corpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jp_corpoLayout.createSequentialGroup()
                            .addComponent(jbtn_all)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtn_costumers)
                            .addGap(111, 111, 111)
                            .addComponent(jbtn_products))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jp_corpoLayout.setVerticalGroup(
            jp_corpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_corpoLayout.createSequentialGroup()
                .addGroup(jp_corpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_corpoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jl_costumers)
                        .addGap(18, 18, 18)
                        .addComponent(jcb_costumers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp_corpoLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jl_products)
                        .addGap(18, 18, 18)
                        .addComponent(jcb_products, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp_corpoLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jbtn_seachCostumers))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_corpoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbtn_seachProducts)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jp_corpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_products)
                    .addComponent(jbtn_costumers)
                    .addComponent(jbtn_all))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        jl_title.setFont(new java.awt.Font("BadaBoom BB", 0, 40)); // NOI18N
        jl_title.setForeground(new java.awt.Color(255, 255, 255));
        jl_title.setText("Reportes de ventas");

        javax.swing.GroupLayout jp_headLayout = new javax.swing.GroupLayout(jp_head);
        jp_head.setLayout(jp_headLayout);
        jp_headLayout.setHorizontalGroup(
            jp_headLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_corpo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_headLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jl_title)
                .addGap(127, 127, 127))
        );
        jp_headLayout.setVerticalGroup(
            jp_headLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_headLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jl_title, javax.swing.GroupLayout.PREFERRED_SIZE, 48, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jp_corpo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_head, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jp_head, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_costumersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_costumersActionPerformed
        costumers();
    }//GEN-LAST:event_jbtn_costumersActionPerformed

    private void jbtn_allActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_allActionPerformed
        all();
    }//GEN-LAST:event_jbtn_allActionPerformed

    private void jbtn_seachCostumersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_seachCostumersActionPerformed
        searchCostumers();
    }//GEN-LAST:event_jbtn_seachCostumersActionPerformed

    private void jbtn_seachProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_seachProductsActionPerformed
        searchProducts();
    }//GEN-LAST:event_jbtn_seachProductsActionPerformed

    private void jbtn_productsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_productsActionPerformed
        products();
    }//GEN-LAST:event_jbtn_productsActionPerformed
    
    public void all(){
        dtm =  (DefaultTableModel) this.jt_data.getModel();
        dtm.setColumnIdentifiers(new Object[]{"Nombre","RFC","Producto","Cantidad","Precio","Total"});
        this.jt_data.setModel(dtm);
        clean();
        cb.Connection("rollback", "root", "1234");
        try {
            rs = cb.query("select * from reportes");
            while(rs.next()){
                dtm.addRow(new Object[]{rs.getString("nombre"),rs.getString("rfc"), rs.getString("producto"), rs.getString("cantidad"), rs.getString("precio"), rs.getString("Total")});
            }
        } catch (Exception e) {
        }
        report("src\\reportes\\Todo.jrxml");
    }
    
    public void products(){
        dtm =  (DefaultTableModel) this.jt_data.getModel();
        dtm.setColumnIdentifiers(new Object[]{"Producto","Cantidad","Total"});
        this.jt_data.setModel(dtm);
        clean();
        cb.Connection("rollback", "root", "1234");
        try {
            rs = cb.query("select producto, sum(cantidad) as cantidad, sum(Total) as total from reportes group by producto;");
            while(rs.next()){
                dtm.addRow(new Object[]{rs.getString("producto"),rs.getString("cantidad"), rs.getString("Total")});
            }
        } catch (Exception e) {
        }
        report("src\\reportes\\TotalProducts.jrxml");
    }
    
    public void costumers(){
        dtm =  (DefaultTableModel) this.jt_data.getModel();
        dtm.setColumnIdentifiers(new Object[]{"Nombre","RFC","Total"});
        this.jt_data.setModel(dtm);
        clean();
        cb.Connection("rollback", "root", "1234");
        try {
            rs = cb.query("select nombre, rfc, sum(Total) as total from reportes group by nombre;");
            while(rs.next()){
                dtm.addRow(new Object[]{rs.getString("nombre"),rs.getString("rfc"), rs.getString("Total")});
            }
        } catch (Exception e) {
        }
        report("src\\reportes\\totalCustomer.jrxml");
    }
    
    
    public void searchCostumers(){
        reportSpecific("src\\reportes\\SpecificCostumers.jrxml", (String) this.jcb_costumers.getSelectedItem());
        dtm =  (DefaultTableModel) this.jt_data.getModel();
        dtm.setColumnIdentifiers(new Object[]{"Nombre","Producto","RFC","Cantidad","Precio","Total"});
        this.jt_data.setModel(dtm);
        clean();
        cb.Connection("rollback", "root", "1234");
        try {
            rs = cb.query("select * from reportes where nombre="+"'"+(String)this.jcb_costumers.getSelectedItem()+"'");
            while(rs.next()){
                dtm.addRow(new Object[]{rs.getString("nombre"),rs.getString("rfc"),rs.getString("producto"),rs.getString("cantidad"),rs.getString("precio"),rs.getString("Total")});
            }
        } catch (Exception e) {
        }
    }
    
    public void reportSpecific(String address, String parameter){
        if(JOptionPane.showConfirmDialog(this, "Desea ver el reporte","Rrportes", 2, 1) == 0){
            Map name = new HashMap();
            name.put("name", parameter);
            try {
                JasperReport report = JasperCompileManager.compileReport(address);
                JasperPrint viewReport = JasperFillManager.fillReport(report, name, cb.Connection("rollback", "root", "1234"));
                window = new JasperViewer(viewReport,false);
                window.setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
                window.setSize(window.getMaximumSize());
                window.setExtendedState(window.MAXIMIZED_BOTH);
                window.setVisible(true);
            } catch (Exception e) {
            }
        }
    }
    
    public void searchProducts(){
        reportSpecific("src\\reportes\\SpecificProducts.jrxml", (String) this.jcb_products.getSelectedItem());
        dtm =  (DefaultTableModel) this.jt_data.getModel();
        dtm.setColumnIdentifiers(new Object[]{"Nombre","Producto","RFC","Cantidad","Precio","Total"});
        this.jt_data.setModel(dtm);
        clean();
        cb.Connection("rollback", "root", "1234");
        try {
            rs = cb.query("select * from reportes where producto="+"'"+(String)this.jcb_products.getSelectedItem()+"'");
            while(rs.next()){
                dtm.addRow(new Object[]{rs.getString("nombre"),rs.getString("rfc"),rs.getString("producto"),rs.getString("cantidad"),rs.getString("precio"),rs.getString("Total")});
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
    
    public void report(String address){
        if(JOptionPane.showConfirmDialog(this, "Desea ver el reporte","Rrportes", 2, 1) == 0){
            try {
                JasperReport report = JasperCompileManager.compileReport(address);
                JasperPrint viewReport = JasperFillManager.fillReport(report, null, cb.Connection("rollback", "root", "1234"));
                window = new JasperViewer(viewReport,false);
                window.setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
                window.setSize(window.getMaximumSize());
                window.setExtendedState(window.MAXIMIZED_BOTH);
                window.setVisible(true);
            } catch (Exception e) {
                System.err.printf("Error al generar el reporte");
            }
        }
    }
    
    public void clean(){
        dtm = (DefaultTableModel) this.jt_data.getModel();
        while (dtm.getRowCount() > 0) {            
            dtm.removeRow(0);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reportes().setVisible(true);
            }
        });
    }
    
    public void llenarComboBox(){
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtn_all;
    private javax.swing.JButton jbtn_costumers;
    private javax.swing.JButton jbtn_products;
    private javax.swing.JButton jbtn_seachCostumers;
    private javax.swing.JButton jbtn_seachProducts;
    private javax.swing.JComboBox<String> jcb_costumers;
    private javax.swing.JComboBox<String> jcb_products;
    private javax.swing.JLabel jl_costumers;
    private javax.swing.JLabel jl_products;
    private javax.swing.JLabel jl_title;
    private javax.swing.JPanel jp_corpo;
    private javax.swing.JPanel jp_head;
    private javax.swing.JTable jt_data;
    // End of variables declaration//GEN-END:variables
}
